version: '2'
services:
  http-middleware:
    build:
      context: ./envoy
      dockerfile: Dockerfile-envoy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - "80"
      - "8080"
    mem_limit: 64MB
  another-api:
    build: 
      context: ./another-api
      dockerfile: Dockerfile-another-api
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/code
